// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Tiny base64 previews shown while the real image loads (next/image `blurDataURL`).

export const blurMap: Record<string, string> = {
  "/works/blubees/bg-showcase.png": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAcAA4BaJYgCdAEOO/JoAAD++Lmr0OizAv2rJqUAJYW6U5UydwUnh/0AAA==",
  "/works/blubees/inst-home.jpg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAgCdASoGAAwAA4BaJbACdGuAt/8D0N30AGAAAPzZeGHTgJk7ZOQMAqJxX/uqCmzvMbJj9yv6TKVK7gkyfcw+sO5yW2jwjN4yL/56mWgKAAAA",
  "/works/facilio-helpdesk-ai/hero.jpg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAcAA4BaJbACdAC9WdBugADN8T1K58bk7HHOLPPLMcRqjFXN/JvZGb6mz2fvraorAAedhgAAAA==",
  "/works/iot-automation/bg-atrium.jpg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoMAAcAA4BaJbACdADYCUAA/uWgRPrwu3omEXpVIpBBNDG0snQ+Pem7Z2rY/Ct9uO45Q7GVccAAAA==",
  "/works/iot-automation/home-on.jpg": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoGAAwAA4BaJYwCdH8AGBvh//QAAP7wSN9Mrab9Mc7LV+fs1VCtTMQou5Qsy1L86ljPXGVAAAA=",
  "/works/mellow/bg-sky.jpg": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoMAAkAA4BaJbACdADaLpTAAP5JwiHoezCaR4XrvRgP7bMfLq13wVCk99nSFHJyrSa4eEn429UtIUSP/o83mBXxZOAAAA==",
  "/works/mellow/hero-cover.jpg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAcAA4BaJZgCdAEO1nnkUADOPdBwE1sNo/kavnBZAwNSEzMpoGIviBHgNYffYM19PAhN8EAAAA==",
  "/works/mellow/home-attention.jpg": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoMAAcAA4BaJaQAA3AA/vSoM52EJQAA",
}

/** Placeholder props for next/image; empty when no preview exists for `src`. */
export function blurProps(src: string): { placeholder: 'blur'; blurDataURL: string } | Record<string, never> {
  const blurDataURL = blurMap[src]
  return blurDataURL ? { placeholder: 'blur', blurDataURL } : {}
}
