// Generates tiny blur placeholders for every image referenced in
// content/works.ts and writes them to content/blur.ts. Runs automatically
// before `next build` (see the `prebuild` script); run `npm run blur` by hand
// after adding or replacing a card image to refresh it in dev.
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import sharp from 'sharp'

const root = new URL('..', import.meta.url).pathname
const registry = await readFile(join(root, 'content/works.ts'), 'utf8')

// Only the registry is scanned, deliberately: the map is imported by the home
// grid, so keeping it to card images keeps the home bundle small.
const paths = [...new Set(registry.match(/'\/[^']+\.(?:jpe?g|png|webp)'/g) ?? [])]
  .map((s) => s.slice(1, -1))
  .sort()

const entries = []
for (const src of paths) {
  const { data, info } = await sharp(join(root, 'public', src))
    .rotate()
    .resize(12, 12, { fit: 'inside' })
    .webp({ quality: 40 })
    .toBuffer({ resolveWithObject: true })
  entries.push([src, `data:image/${info.format};base64,${data.toString('base64')}`])
}

const body = entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n')
const out = `// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Tiny base64 previews shown while the real image loads (next/image \`blurDataURL\`).

export const blurMap: Record<string, string> = {
${body}
}

/** Placeholder props for next/image; empty when no preview exists for \`src\`. */
export function blurProps(src: string): { placeholder: 'blur'; blurDataURL: string } | Record<string, never> {
  const blurDataURL = blurMap[src]
  return blurDataURL ? { placeholder: 'blur', blurDataURL } : {}
}
`
await writeFile(join(root, 'content/blur.ts'), out)
console.log(`wrote content/blur.ts with ${entries.length} placeholders`)
